version 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm 1
      - save_cashe:
          key: "npm-package"
          paths:
            - /src/node_modules
      - run: npm run lint

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cashe:
          keys:
            - "npm-packages"
      - run: npm 1
      - run: npm run

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cashe:
          keys:
            - "npm-packages"
      - run: npm audit

workflows:
  my_work_flows:
   jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test